server.port=8083
spring.application.name=api-gateway
spring.cloud.gateway.server.webflux.routes[0].id=customer
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CUSTOMER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/customers/**
spring.cloud.gateway.server.webflux.trusted-proxies=192\\.168\\..*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true